### PR TITLE
DatePicker

### PR DESCRIPTION
**Pull request by donibehrami**

### CODE REVIEW

**Comment by donibehrami** [comment]
Save button only closes the date picker, shall I remove it?

**Comment by gentgaashi** [comment]
No point having it, unless it "saves something", when you can click away to remove it :)

**Comment by gentgaashi** [comment]
Still a bug when hovering over 'SAT' table cell

**Comment by gentgaashi** [comment]
and there is too much space at the bottom, it should be the same as on the side

**Comment by donibehrami** [comment]
weird enough, i fixed that bottom space... on it.

**Pull request merged**
