### PR TITLE
Headings initial commit

### PR DESCRIPTION
**Pull request by donibehrami**

### CODE REVIEW

**Comment by gentgaashi** [comment]
Is the work done here? @donibehrami

**Comment by donibehrami** [comment]
@gentgaashi Yes.

**Comment by gentgaashi** [comment]
Make sure the font sizes are correct, pick the biggest font-size title you find in the front end platform, assign it to h1, and then go from there to smaller ones assigning h2, h3 ..... , because for example, the default font size for h1 might not be the same as the default size for the h1 in the front end platform. @donibehrami

**Comment by gentgaashi** [comment]
ok nice, merging this to develop

**Pull request merged**
